### ISSUE TITLE
GenerateaccountID returns 0

### ISSUE THREAD

**Issue by ghost** [Jaguar0625/JavaScriptNrs#1]
There seems to be some sort of bug in the generateAccount Id function; 

It returns 0 like 1 in 50 times..

It generates the public Key correctly, but when passed to converters.hexStringToByteArray() it returns 

0000000000000000000000000000000000000000000000000000000000000000

(which then results in account ID 0).

This on safari, mac.

No errors in console.

Any idea what's going on?

**Comment by Jaguar0625** [comment]
What generateAccountId function? In its current form the code just has the curve / crypto code. I assume you're building something on top of it?

**Comment by ghost** [comment]
Seems you are right, I added this function: 

```
function getAccountId (secretPhrase) {
    var publicKey = getPublicKey(converters.stringToHexString(secretPhrase));
    var hex = converters.hexStringToByteArray(publicKey);

    hash.init();
    hash.update(hex);
    var account = hash.getBytes();
    account = converters.byteArrayToHexString(account);
    var slice   = (converters.hexStringToByteArray(account)).slice(0,8);
    return byteArrayToBigInteger(slice).toString();
}

function byteArrayToBigInteger (byteArray, startIndex) {
    var value = new BigInteger("0",10);
    var temp1,temp2;
    for ( var i = byteArray.length - 1; i >= 0; i--) {
        temp1 = value.multiply(new BigInteger("256",10));
        temp2 = temp1.add(new BigInteger(byteArray[i].toString(10),10));
        value = temp2;
    }
    return value;
}
```

Which uses jsbn.js and jsbn2.js from here: http://www-cs-students.stanford.edu/~tjw/jsbn/

Anyway it works correctly if I submit the form (code not included here), even submit it tens of times, but then when I let it sit there for a while and submit again, the account id returned is always zero. Not sure why that timing matters?!

Anyway, it seems to be an issue with the SHA256 functions. The init returns a different array from when I compare it to earlier requests that did succeed. I'm not sure what the issue could be..
